In [1]:
import pandas as pd 

In [2]:
import numpy as np 

In [3]:
dfs=pd.read_csv("C:\\Users\\Legion\\OneDrive\\Desktop\\data\\spam.csv")

In [4]:
dfs

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will �_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [5]:
dfs.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [6]:
dfs.isna().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [7]:
dfs.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1,inplace=True)

In [8]:
dfs

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
dfs.columns

Index(['v1', 'v2'], dtype='object')

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
lab=LabelEncoder()

In [12]:
lab

LabelEncoder()

In [13]:
lab.fit(dfs['v1'])

LabelEncoder()

In [14]:
lab.transform(dfs['v1'])

array([0, 0, 1, ..., 0, 0, 0])

In [15]:
lab.classes_

array(['ham', 'spam'], dtype=object)

In [16]:
a=lab.transform(dfs['v1'])

In [17]:
a

array([0, 0, 1, ..., 0, 0, 0])

In [18]:
dfs["v11"]=a

In [19]:
dfs

v1                                                 v2  v11
0      ham  Go until jurong point, crazy.. Available only ...    0
1      ham                      Ok lar... Joking wif u oni...    0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...    1
3      ham  U dun say so early hor... U c already then say...    0
4      ham  Nah I don't think he goes to usf, he lives aro...    0
...    ...                                                ...  ...
5567  spam  This is the 2nd time we have tried 2 contact u...    1
5568   ham              Will �_ b going to esplanade fr home?    0
5569   ham  Pity, * was in mood for that. So...any other s...    0
5570   ham  The guy did some bitching but I acted like i'd...    0
5571   ham                         Rofl. Its true to its name    0

[5572 rows x 3 columns]

In [20]:
dfs.drop("v1",axis=1,inplace=True)

In [21]:
dfs.columns

Index(['v2', 'v11'], dtype='object')

In [22]:
dfs.columns=["v2","v1"]

In [23]:
dfs

v2  v1
0     Go until jurong point, crazy.. Available only ...   0
1                         Ok lar... Joking wif u oni...   0
2     Free entry in 2 a wkly comp to win FA Cup fina...   1
3     U dun say so early hor... U c already then say...   0
4     Nah I don't think he goes to usf, he lives aro...   0
...                                                 ...  ..
5567  This is the 2nd time we have tried 2 contact u...   1
5568              Will �_ b going to esplanade fr home?   0
5569  Pity, * was in mood for that. So...any other s...   0
5570  The guy did some bitching but I acted like i'd...   0
5571                         Rofl. Its true to its name   0

[5572 rows x 2 columns]

In [24]:
dfs["v1"].unique()

array([0, 1])

In [25]:
dfs["v1"].value_counts

<bound method IndexOpsMixin.value_counts of 0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: v1, Length: 5572, dtype: int32>

In [26]:
x=dfs.drop("v1",axis=1)

In [27]:
x

v2
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
...                                                 ...
5567  This is the 2nd time we have tried 2 contact u...
5568              Will �_ b going to esplanade fr home?
5569  Pity, * was in mood for that. So...any other s...
5570  The guy did some bitching but I acted like i'd...
5571                         Rofl. Its true to its name

[5572 rows x 1 columns]

In [28]:
y=dfs["v1"]

In [29]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: v1, Length: 5572, dtype: int32

In [30]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [31]:
 x.shape

(5572, 1)

In [32]:
y.shape

(5572,)

In [33]:
from imblearn.over_sampling import RandomOverSampler

In [34]:
ros= RandomOverSampler()

In [35]:
ros

RandomOverSampler()

In [36]:
x_ros,y_ros=ros.fit_resample(x,y)

In [37]:
x_ros.shape

(9650, 1)

In [38]:
y_ros.shape

(9650,)

In [39]:
y_ros.value_counts()

0    4825
1    4825
Name: v1, dtype: int64

In [40]:
from imblearn.under_sampling import RandomUnderSampler

In [41]:
rus=RandomUnderSampler()

In [42]:
rus

RandomUnderSampler()

In [43]:
x_rus,y_rus=rus.fit_resample(x,y)

In [44]:
x_rus.shape

(1494, 1)

In [45]:
y_rus.shape

(1494,)

In [46]:
y_rus.value_counts()

0    747
1    747
Name: v1, dtype: int64

In [51]:
dfs.head()

v2  v1
0  Go until jurong point, crazy.. Available only ...   0
1                      Ok lar... Joking wif u oni...   0
2  Free entry in 2 a wkly comp to win FA Cup fina...   1
3  U dun say so early hor... U c already then say...   0
4  Nah I don't think he goes to usf, he lives aro...   0