In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
dfcar=pd.read_csv("C:\\Users\\Legion\\OneDrive\\Desktop\\data\\cars.csv")

In [4]:
dfcar

brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [5]:
dfcar["owner"]

0                First Owner
1               Second Owner
2                Third Owner
3                First Owner
4                First Owner
                ...         
8123             First Owner
8124    Fourth & Above Owner
8125             First Owner
8126             First Owner
8127             First Owner
Name: owner, Length: 8128, dtype: object

In [6]:
dfcar.isna().sum()

brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
oe=OrdinalEncoder()

In [9]:
oe.fit(dfcar[["owner"]])

OrdinalEncoder()

In [10]:
oe.transform(dfcar[["owner"]])

array([[0.],
       [2.],
       [4.],
       ...,
       [0.],
       [0.],
       [0.]])

In [11]:
a=oe.transform(dfcar[["owner"]])

In [12]:
a

array([[0.],
       [2.],
       [4.],
       ...,
       [0.],
       [0.],
       [0.]])

In [13]:
dfa=pd.DataFrame(a,columns=["owner_encoding"],dtype="int")

In [14]:
dfa

owner_encoding
0                  0
1                  2
2                  4
3                  0
4                  0
...              ...
8123               0
8124               1
8125               0
8126               0
8127               0

[8128 rows x 1 columns]

In [15]:
pd.concat([dfcar,dfa],axis=1)

brand  km_driven    fuel                 owner  selling_price  \
0      Maruti     145500  Diesel           First Owner         450000   
1       Skoda     120000  Diesel          Second Owner         370000   
2       Honda     140000  Petrol           Third Owner         158000   
3     Hyundai     127000  Diesel           First Owner         225000   
4      Maruti     120000  Petrol           First Owner         130000   
...       ...        ...     ...                   ...            ...   
8123  Hyundai     110000  Petrol           First Owner         320000   
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000   
8125   Maruti     120000  Diesel           First Owner         382000   
8126     Tata      25000  Diesel           First Owner         290000   
8127     Tata      25000  Diesel           First Owner         290000   

      owner_encoding  
0                  0  
1                  2  
2                  4  
3                  0  
4                  0  
...              ...  
8123               0  
8124               1  
8125               0  
8126               0  
8127               0  

[8128 rows x 6 columns]

In [18]:
dfcar["encoding"]=a

In [19]:
dfcar

brand  km_driven    fuel                 owner  selling_price  \
0      Maruti     145500  Diesel           First Owner         450000   
1       Skoda     120000  Diesel          Second Owner         370000   
2       Honda     140000  Petrol           Third Owner         158000   
3     Hyundai     127000  Diesel           First Owner         225000   
4      Maruti     120000  Petrol           First Owner         130000   
...       ...        ...     ...                   ...            ...   
8123  Hyundai     110000  Petrol           First Owner         320000   
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000   
8125   Maruti     120000  Diesel           First Owner         382000   
8126     Tata      25000  Diesel           First Owner         290000   
8127     Tata      25000  Diesel           First Owner         290000   

      encoding  
0          0.0  
1          2.0  
2          4.0  
3          0.0  
4          0.0  
...        ...  
8123       0.0  
8124       1.0  
8125       0.0  
8126       0.0  
8127       0.0  

[8128 rows x 6 columns]

In [20]:
dfcar["brand"]

0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...   
8123    Hyundai
8124    Hyundai
8125     Maruti
8126       Tata
8127       Tata
Name: brand, Length: 8128, dtype: object

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
ohe=OneHotEncoder()

In [39]:
ohe.fit(dfcar[["brand"]])

OneHotEncoder()

In [24]:
ohe.transform(dfcar[["brand"]])

<8128x32 sparse matrix of type '<class 'numpy.float64'>'
	with 8128 stored elements in Compressed Sparse Row format>

In [26]:
ohe.transform(dfcar[["brand"]]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
b=ohe.transform(dfcar[["brand"]]).toarray()

In [28]:
b

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
ohe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'], dtype=object)]

In [31]:
dfohe=pd.DataFrame(b,columns=['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'],dtype="int")

In [32]:
dfohe

Ambassador  Ashok  Audi  BMW  Chevrolet  Daewoo  Datsun  Fiat  Force  \
0              0      0     0    0          0       0       0     0      0   
1              0      0     0    0          0       0       0     0      0   
2              0      0     0    0          0       0       0     0      0   
3              0      0     0    0          0       0       0     0      0   
4              0      0     0    0          0       0       0     0      0   
...          ...    ...   ...  ...        ...     ...     ...   ...    ...   
8123           0      0     0    0          0       0       0     0      0   
8124           0      0     0    0          0       0       0     0      0   
8125           0      0     0    0          0       0       0     0      0   
8126           0      0     0    0          0       0       0     0      0   
8127           0      0     0    0          0       0       0     0      0   

      Ford  ...  Mitsubishi  Nissan  Opel  Peugeot  Renault  Skoda  Tata  \
0        0  ...           0       0     0        0        0      0     0   
1        0  ...           0       0     0        0        0      1     0   
2        0  ...           0       0     0        0        0      0     0   
3        0  ...           0       0     0        0        0      0     0   
4        0  ...           0       0     0        0        0      0     0   
...    ...  ...         ...     ...   ...      ...      ...    ...   ...   
8123     0  ...           0       0     0        0        0      0     0   
8124     0  ...           0       0     0        0        0      0     0   
8125     0  ...           0       0     0        0        0      0     0   
8126     0  ...           0       0     0        0        0      0     1   
8127     0  ...           0       0     0        0        0      0     1   

      Toyota  Volkswagen  Volvo  
0          0           0      0  
1          0           0      0  
2          0           0      0  
3          0           0      0  
4          0           0      0  
...      ...         ...    ...  
8123       0           0      0  
8124       0           0      0  
8125       0           0      0  
8126       0           0      0  
8127       0           0      0  

[8128 rows x 32 columns]

In [33]:
pd.concat([dfcar,dfohe],axis=1)

brand  km_driven    fuel                 owner  selling_price  \
0      Maruti     145500  Diesel           First Owner         450000   
1       Skoda     120000  Diesel          Second Owner         370000   
2       Honda     140000  Petrol           Third Owner         158000   
3     Hyundai     127000  Diesel           First Owner         225000   
4      Maruti     120000  Petrol           First Owner         130000   
...       ...        ...     ...                   ...            ...   
8123  Hyundai     110000  Petrol           First Owner         320000   
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000   
8125   Maruti     120000  Diesel           First Owner         382000   
8126     Tata      25000  Diesel           First Owner         290000   
8127     Tata      25000  Diesel           First Owner         290000   

      encoding  Ambassador  Ashok  Audi  BMW  ...  Mitsubishi  Nissan  Opel  \
0          0.0           0      0     0    0  ...           0       0     0   
1          2.0           0      0     0    0  ...           0       0     0   
2          4.0           0      0     0    0  ...           0       0     0   
3          0.0           0      0     0    0  ...           0       0     0   
4          0.0           0      0     0    0  ...           0       0     0   
...        ...         ...    ...   ...  ...  ...         ...     ...   ...   
8123       0.0           0      0     0    0  ...           0       0     0   
8124       1.0           0      0     0    0  ...           0       0     0   
8125       0.0           0      0     0    0  ...           0       0     0   
8126       0.0           0      0     0    0  ...           0       0     0   
8127       0.0           0      0     0    0  ...           0       0     0   

      Peugeot  Renault  Skoda  Tata  Toyota  Volkswagen  Volvo  
0           0        0      0     0       0           0      0  
1           0        0      1     0       0           0      0  
2           0        0      0     0       0           0      0  
3           0        0      0     0       0           0      0  
4           0        0      0     0       0           0      0  
...       ...      ...    ...   ...     ...         ...    ...  
8123        0        0      0     0       0           0      0  
8124        0        0      0     0       0           0      0  
8125        0        0      0     0       0           0      0  
8126        0        0      0     1       0           0      0  
8127        0        0      0     1       0           0      0  

[8128 rows x 38 columns]

In [34]:
dfcar["fuel"]

0       Diesel
1       Diesel
2       Petrol
3       Diesel
4       Petrol
         ...  
8123    Petrol
8124    Diesel
8125    Diesel
8126    Diesel
8127    Diesel
Name: fuel, Length: 8128, dtype: object

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
ohe1=OneHotEncoder()

In [38]:
ohe1.fit(dfcar[["fuel"]])

OneHotEncoder()

In [40]:
ohe1.transform(dfcar[["fuel"]])

<8128x4 sparse matrix of type '<class 'numpy.float64'>'
	with 8128 stored elements in Compressed Sparse Row format>

In [41]:
ohe1.transform(dfcar[["fuel"]]).toarray()

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]])

In [42]:
c=ohe1.transform(dfcar[["fuel"]]).toarray()

In [43]:
c

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]])

In [44]:
ohe1.categories_

[array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [45]:
dfohe1=pd.DataFrame(c,columns=['CNG', 'Diesel', 'LPG', 'Petrol'],dtype="int")

In [46]:
dfohe1

CNG  Diesel  LPG  Petrol
0       0       1    0       0
1       0       1    0       0
2       0       0    0       1
3       0       1    0       0
4       0       0    0       1
...   ...     ...  ...     ...
8123    0       0    0       1
8124    0       1    0       0
8125    0       1    0       0
8126    0       1    0       0
8127    0       1    0       0

[8128 rows x 4 columns]

In [47]:
pd.concat([dfcar,dfohe1],axis=1)

brand  km_driven    fuel                 owner  selling_price  \
0      Maruti     145500  Diesel           First Owner         450000   
1       Skoda     120000  Diesel          Second Owner         370000   
2       Honda     140000  Petrol           Third Owner         158000   
3     Hyundai     127000  Diesel           First Owner         225000   
4      Maruti     120000  Petrol           First Owner         130000   
...       ...        ...     ...                   ...            ...   
8123  Hyundai     110000  Petrol           First Owner         320000   
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000   
8125   Maruti     120000  Diesel           First Owner         382000   
8126     Tata      25000  Diesel           First Owner         290000   
8127     Tata      25000  Diesel           First Owner         290000   

      encoding  CNG  Diesel  LPG  Petrol  
0          0.0    0       1    0       0  
1          2.0    0       1    0       0  
2          4.0    0       0    0       1  
3          0.0    0       1    0       0  
4          0.0    0       0    0       1  
...        ...  ...     ...  ...     ...  
8123       0.0    0       0    0       1  
8124       1.0    0       1    0       0  
8125       0.0    0       1    0       0  
8126       0.0    0       1    0       0  
8127       0.0    0       1    0       0  

[8128 rows x 10 columns]